import { CheckBox, Button, StandardButton, Button, ComboBox } from "std-widgets.slint";
import { SettingsWindow } from "settings-window.slint";


export component MainWindow inherits Window{
               min-width: 200px;
               min-height: 400px;
                in-out property<string> bit_price: "Loading...";
                in-out property <brush> background_color;
                in-out property <brush> text_color;
                in-out property <string> coin_name;

                callback open_settings;
                callback mouse_move(length,length);
                TouchArea {
                moved => {
                root.mouse_move(self.mouse-x - self.pressed-x , self.mouse-y - self.pressed-y);
                }
                }

        title: "Live Info";
        background: transparent;
          Rectangle {
               width: 200px;
               height: 400px;
               background: root.background_color;

               Rectangle {
                   width: 100%;
                   height: 30px;
                   background: #FF9900;
                   x: 0;
                   y: parent.y - 1px;
                   Text {
                    font-size: 1rem;
                    font-weight: 900;
                    x:parent.x + 10px;
                    padding: 10px;
                    text: root.coin_name +": $" + root.bit_price;
                    color: root.text_color;

                   }
               }
           }
           MenuBar {
            Menu {
                title: "Settings";
                MenuItem {
                title: "Open";
                activated => {
                root.open_settings()
                }
                }

                }

            }
                            popup := PopupWindow{
                            Rectangle {
                            height: 100%;
                            width: 100%;
                            background: #000;
                            }
                            }
/*        pointer-event(event) => {
            if(event.button == PointerEventButton.right){

            popup.show();
            }
        }*/
    }

/*
export component SettingsWindow inherits Window{
               min-width: 500px;
               min-height: 600px;
               background: #000;

}
*/

export component SettingsWindow inherits Window{
//    callback open_settings();
    in-out property <string> coin_name;
    
    min-height: 200px;
    min-width: 200px;
    background: #000;

    title: "Settings";
    full-screen: true;

    cb := ComboBox {
    min-height: 200px;
    min-width: 200px;
    model: ["BTC","ETH"];
    selected(current-value) => {change_value()}
     }


    coin_name: cb.current-value;
     Text {
     height: 100px;
     width: 200px;
     text: coin_name;
     }
     
     callback change_value;



}