import { ComboBox, CheckBox } from "std-widgets.slint";
export component SettingsWindow inherits Window{
    callback open_settings();

    min-height: 200px;
    min-width: 200px;


    cb := ComboBox {
        y: 0px;
        height: 40%;
        width: 40%;
        model: check.checked ? ["other"] : ["ETH","BTC"] ;
    }

    check := CheckBox {
        toggled => {
        cb.current-value = " ";
        }
    }

}